// This file is auto-generated by @hey-api/openapi-ts

export type ActiveModelPublicResponse = {
    data: (ModelArtifactPublic | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_models_upload_model_artifact = {
    model_file: (Blob | File);
    metadata_json: string;
};

export type DashboardSummary = {
    total_patients: number;
    high_risk_patients: number;
    alerts_sent: number;
    last_update?: (string | null);
    active_model?: (ModelArtifactPublic | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type ModelArtifactPublic = {
    id: string;
    created_at?: (string | null);
    client_version_id?: (string | null);
    source_run_id?: (string | null);
    trained_at_utc?: (string | null);
    algorithm: string;
    hyperparameters: {
        [key: string]: unknown;
    };
    metrics: {
        [key: string]: unknown;
    };
    dataset_info: {
        [key: string]: unknown;
    };
    notes?: (string | null);
    is_active: boolean;
    content_type?: (string | null);
    model_size_bytes: number;
    model_sha256: string;
};

export type ModelArtifactsPublic = {
    data: Array<ModelArtifactPublic>;
    count: number;
};

export type ModelArtifactUploadResponse = {
    id: string;
    created_at?: (string | null);
    client_version_id?: (string | null);
    source_run_id?: (string | null);
    algorithm: string;
    is_active: boolean;
    model_size_bytes: number;
    model_sha256: string;
    content_type?: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PacemakerTelemetryIngest = {
    patient_id: number;
    /**
     * Unix epoch timestamp in seconds (UTC).
     */
    timestamp: number;
    lead_impedance_ohms: number;
    capture_threshold_v: number;
    r_wave_sensing_mv: number;
    battery_voltage_v: number;
    target_fail_next_7d?: (number | null);
    lead_impedance_ohms_rolling_mean_3d?: (number | null);
    lead_impedance_ohms_rolling_mean_7d?: (number | null);
    capture_threshold_v_rolling_mean_3d?: (number | null);
    capture_threshold_v_rolling_mean_7d?: (number | null);
    lead_impedance_ohms_delta_per_day_3d?: (number | null);
    lead_impedance_ohms_delta_per_day_7d?: (number | null);
    capture_threshold_v_delta_per_day_3d?: (number | null);
    capture_threshold_v_delta_per_day_7d?: (number | null);
};

export type PacemakerTelemetryIngestResult = {
    received_count: number;
    inserted_count: number;
    duplicate_count: number;
    duplicate_in_payload_count: number;
    duplicate_existing_count: number;
};

/**
 * Single telemetry row returned by the training-data download endpoint.
 */
export type PacemakerTelemetryPublic = {
    id: string;
    patient_id: number;
    timestamp: string;
    lead_impedance_ohms: number;
    capture_threshold_v: number;
    r_wave_sensing_mv: number;
    battery_voltage_v: number;
    target_fail_next_7d?: (number | null);
    lead_impedance_ohms_rolling_mean_3d?: (number | null);
    lead_impedance_ohms_rolling_mean_7d?: (number | null);
    capture_threshold_v_rolling_mean_3d?: (number | null);
    capture_threshold_v_rolling_mean_7d?: (number | null);
    lead_impedance_ohms_delta_per_day_3d?: (number | null);
    lead_impedance_ohms_delta_per_day_7d?: (number | null);
    capture_threshold_v_delta_per_day_3d?: (number | null);
    capture_threshold_v_delta_per_day_7d?: (number | null);
};

export type PatientLatestTelemetryPublic = {
    patient_id: number;
    timestamp: string;
    lead_impedance_ohms: number;
    capture_threshold_v: number;
    r_wave_sensing_mv: number;
    battery_voltage_v: number;
    lead_impedance_ohms_rolling_mean_3d?: (number | null);
    lead_impedance_ohms_rolling_mean_7d?: (number | null);
    capture_threshold_v_rolling_mean_3d?: (number | null);
    capture_threshold_v_rolling_mean_7d?: (number | null);
    lead_impedance_ohms_delta_per_day_3d?: (number | null);
    lead_impedance_ohms_delta_per_day_7d?: (number | null);
    capture_threshold_v_delta_per_day_3d?: (number | null);
    capture_threshold_v_delta_per_day_7d?: (number | null);
    fail_probability?: (number | null);
    created_at?: (string | null);
};

export type PatientLatestTelemetryPublicList = {
    data: Array<PatientLatestTelemetryPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Response envelope for GET /training/download.
 */
export type TrainingDataDownloadResult = {
    rows: Array<PacemakerTelemetryPublic>;
    count: number;
    /**
     * Unix epoch seconds of the newest telemetry row on the server.
     */
    server_newest_ts?: (number | null);
    /**
     * Unix epoch seconds of the maturity boundary (server_newest_ts − 7 days). Only rows with timestamp <= this value are returned.
     */
    maturity_cutoff_ts?: (number | null);
};

/**
 * Response model when creating or inspecting a training job request.
 */
export type TrainingJobRequestPublic = {
    id: string;
    created_at?: (string | null);
    is_pending: boolean;
    requested_by?: (string | null);
    consumed_at?: (string | null);
    cancelled_at?: (string | null);
};

export type TrainingPredictSummary = {
    rows_upserted: number;
    rows_scored: number;
    model_id?: (string | null);
    queued_job_id?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DashboardGetDashboardSummaryResponse = (DashboardSummary);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModelsListModelArtifactsData = {
    limit?: number;
    skip?: number;
};

export type ModelsListModelArtifactsResponse = (ModelArtifactsPublic);

export type ModelsGetActiveModelArtifactResponse = (ActiveModelPublicResponse);

export type ModelsGetModelArtifactData = {
    modelId: string;
};

export type ModelsGetModelArtifactResponse = (ModelArtifactPublic);

export type ModelsActivateModelArtifactData = {
    modelId: string;
};

export type ModelsActivateModelArtifactResponse = (ModelArtifactPublic);

export type ModelsUploadModelArtifactData = {
    formData: Body_models_upload_model_artifact;
};

export type ModelsUploadModelArtifactResponse = (ModelArtifactUploadResponse);

export type PatientsListLatestPatientTelemetryData = {
    alertFilter?: 'all' | 'sent' | 'none';
    limit?: number;
    patientSearch?: (string | null);
    riskFilter?: 'all' | 'high' | 'medium' | 'low';
    skip?: number;
    sortBy?: 'patient_id' | 'risk_score' | 'lead_impedance' | 'capture_threshold' | 'battery_voltage' | 'last_update';
    sortOrder?: 'asc' | 'desc';
};

export type PatientsListLatestPatientTelemetryResponse = (PatientLatestTelemetryPublicList);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TelemetryIngestTelemetryBulkData = {
    requestBody: Array<PacemakerTelemetryIngest>;
};

export type TelemetryIngestTelemetryBulkResponse = (PacemakerTelemetryIngestResult);

export type TrainingPollTrainingJobResponse = (boolean);

export type TrainingDownloadTrainingDataData = {
    /**
     * Unix epoch seconds of the newest telemetry row the local compute already has.
     */
    newestLocalTs: number;
};

export type TrainingDownloadTrainingDataResponse = (TrainingDataDownloadResult);

export type TrainingCreateTrainingJobRequestResponse = (TrainingJobRequestPublic);

export type TrainingRefreshPatientLatestPredictionsResponse = (TrainingPredictSummary);

export type TrainingClaimTrainingJobResponse = (TrainingJobRequestPublic);

export type TrainingCompleteTrainingJobData = {
    jobId: string;
};

export type TrainingCompleteTrainingJobResponse = (TrainingJobRequestPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);