"""Add training job request table

Revision ID: e38207e9b7d2
Revises: c4f9ab72a1de
Create Date: 2026-03-01 17:59:06.374470

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e38207e9b7d2'
down_revision = 'c4f9ab72a1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_job_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_job_request_is_pending'), 'training_job_request', ['is_pending'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_job_request_is_pending'), table_name='training_job_request')
    op.drop_table('training_job_request')
    # ### end Alembic commands ###
